plugins:
  eslint:
    enabled: true

exclude_patterns:
  - "examples"
  - "src/__fixtures__"
  - "src/__snapshots__"
  - "src/**/*.spec.js"
  - "src/**/*-template.js"

checks:
  argument-count:
    config:
      threshold: 8
  method-complexity:
    config:
      threshold: 15
  method-lines:
    config:
      threshold: 45
