plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc

exclude_patterns:
  - "examples"
  - "src/__fixtures__"
  - "src/__snapshots__"
  - "src/**/*.spec.js"
  - "src/**/*-template.js"
